version: "3.8"
services:
  iipsrv:
    build: .
    volumes:
      - ./data:/data
    environment:
      - VERBOSITY=6
      - LOGFILE=/var/log/iipsrv.log
      - FILESYSTEM_PREFIX=/data/
    entrypoint: ["spawn-fcgi", "-n", "-f", "/iipsrv/iipsrv.fcgi", "-p", "9000"]

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/www
    ports:
      - "8094:80"
